ACHANNELS 1
ADEVICE plughw:1,0 null

CHANNEL 0
MYCALL N0CALL-10
MODEM 1200

KISSPORT 5624
AGWPORT off
IGSERVER euro.aprs2.net
IGLOGIN N0CALL-10 12345
PBEACON sendto=IG delay=0:30 every=60:00 symbol=R& lat=52^00.00N long=021^00.00E comment="Quansheng Web Transceiver APRS IGate"

